//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Assets/EditableSamples/GyroTools/SamplesObjectRotation/InputActions/RotationInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/EditableSamples/GyroTools/SamplesObjectRotation/InputActions/RotationInputs.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @RotationInputs: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @RotationInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""RotationInputs"",
    ""maps"": [
        {
            ""name"": ""Imu"",
            ""id"": ""01bbc29b-da93-45b9-8c95-4b6381262128"",
            ""actions"": [
                {
                    ""name"": ""Motion"",
                    ""type"": ""PassThrough"",
                    ""id"": ""931cf6ad-6e87-4e86-a529-1522ef668930"",
                    ""expectedControlType"": ""IMU"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Quit"",
                    ""type"": ""Button"",
                    ""id"": ""f97fcbd8-68a9-4c5a-a13d-851347252f39"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SizeChange"",
                    ""type"": ""PassThrough"",
                    ""id"": ""300890ee-15a5-4586-8180-7df9cbc03aeb"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DisableGyro"",
                    ""type"": ""Button"",
                    ""id"": ""5d4cef4b-ff9f-4986-885d-d7a617a89e9d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ResetGyro"",
                    ""type"": ""Button"",
                    ""id"": ""c34b2fa8-569d-4b2e-bd72-c1f5eb4ab7f8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""725cb482-d644-4592-aca2-df318d6c7cec"",
                    ""path"": ""<Gamepad>/IMU"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Motion"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""661c14ff-b8bb-4162-ab58-48d885c1113e"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Quit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fd5debd7-a021-4adb-8e33-90d2ec6c561b"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Quit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5120c5b1-d740-49f3-8761-1ecca750ae4d"",
                    ""path"": ""<Gamepad>/leftStick/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SizeChange"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5bb1cf7d-9448-4f83-87f7-985689c50e2b"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DisableGyro"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3c956c0d-af6c-4625-9d02-f14b21d64070"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ResetGyro"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Imu
        m_Imu = asset.FindActionMap("Imu", throwIfNotFound: true);
        m_Imu_Motion = m_Imu.FindAction("Motion", throwIfNotFound: true);
        m_Imu_Quit = m_Imu.FindAction("Quit", throwIfNotFound: true);
        m_Imu_SizeChange = m_Imu.FindAction("SizeChange", throwIfNotFound: true);
        m_Imu_DisableGyro = m_Imu.FindAction("DisableGyro", throwIfNotFound: true);
        m_Imu_ResetGyro = m_Imu.FindAction("ResetGyro", throwIfNotFound: true);
    }

    ~@RotationInputs()
    {
        UnityEngine.Debug.Assert(!m_Imu.enabled, "This will cause a leak and performance issues, RotationInputs.Imu.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Imu
    private readonly InputActionMap m_Imu;
    private List<IImuActions> m_ImuActionsCallbackInterfaces = new List<IImuActions>();
    private readonly InputAction m_Imu_Motion;
    private readonly InputAction m_Imu_Quit;
    private readonly InputAction m_Imu_SizeChange;
    private readonly InputAction m_Imu_DisableGyro;
    private readonly InputAction m_Imu_ResetGyro;
    /// <summary>
    /// Provides access to input actions defined in input action map "Imu".
    /// </summary>
    public struct ImuActions
    {
        private @RotationInputs m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public ImuActions(@RotationInputs wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Imu/Motion".
        /// </summary>
        public InputAction @Motion => m_Wrapper.m_Imu_Motion;
        /// <summary>
        /// Provides access to the underlying input action "Imu/Quit".
        /// </summary>
        public InputAction @Quit => m_Wrapper.m_Imu_Quit;
        /// <summary>
        /// Provides access to the underlying input action "Imu/SizeChange".
        /// </summary>
        public InputAction @SizeChange => m_Wrapper.m_Imu_SizeChange;
        /// <summary>
        /// Provides access to the underlying input action "Imu/DisableGyro".
        /// </summary>
        public InputAction @DisableGyro => m_Wrapper.m_Imu_DisableGyro;
        /// <summary>
        /// Provides access to the underlying input action "Imu/ResetGyro".
        /// </summary>
        public InputAction @ResetGyro => m_Wrapper.m_Imu_ResetGyro;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Imu; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="ImuActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(ImuActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="ImuActions" />
        public void AddCallbacks(IImuActions instance)
        {
            if (instance == null || m_Wrapper.m_ImuActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ImuActionsCallbackInterfaces.Add(instance);
            @Motion.started += instance.OnMotion;
            @Motion.performed += instance.OnMotion;
            @Motion.canceled += instance.OnMotion;
            @Quit.started += instance.OnQuit;
            @Quit.performed += instance.OnQuit;
            @Quit.canceled += instance.OnQuit;
            @SizeChange.started += instance.OnSizeChange;
            @SizeChange.performed += instance.OnSizeChange;
            @SizeChange.canceled += instance.OnSizeChange;
            @DisableGyro.started += instance.OnDisableGyro;
            @DisableGyro.performed += instance.OnDisableGyro;
            @DisableGyro.canceled += instance.OnDisableGyro;
            @ResetGyro.started += instance.OnResetGyro;
            @ResetGyro.performed += instance.OnResetGyro;
            @ResetGyro.canceled += instance.OnResetGyro;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="ImuActions" />
        private void UnregisterCallbacks(IImuActions instance)
        {
            @Motion.started -= instance.OnMotion;
            @Motion.performed -= instance.OnMotion;
            @Motion.canceled -= instance.OnMotion;
            @Quit.started -= instance.OnQuit;
            @Quit.performed -= instance.OnQuit;
            @Quit.canceled -= instance.OnQuit;
            @SizeChange.started -= instance.OnSizeChange;
            @SizeChange.performed -= instance.OnSizeChange;
            @SizeChange.canceled -= instance.OnSizeChange;
            @DisableGyro.started -= instance.OnDisableGyro;
            @DisableGyro.performed -= instance.OnDisableGyro;
            @DisableGyro.canceled -= instance.OnDisableGyro;
            @ResetGyro.started -= instance.OnResetGyro;
            @ResetGyro.performed -= instance.OnResetGyro;
            @ResetGyro.canceled -= instance.OnResetGyro;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="ImuActions.UnregisterCallbacks(IImuActions)" />.
        /// </summary>
        /// <seealso cref="ImuActions.UnregisterCallbacks(IImuActions)" />
        public void RemoveCallbacks(IImuActions instance)
        {
            if (m_Wrapper.m_ImuActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="ImuActions.AddCallbacks(IImuActions)" />
        /// <seealso cref="ImuActions.RemoveCallbacks(IImuActions)" />
        /// <seealso cref="ImuActions.UnregisterCallbacks(IImuActions)" />
        public void SetCallbacks(IImuActions instance)
        {
            foreach (var item in m_Wrapper.m_ImuActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ImuActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="ImuActions" /> instance referencing this action map.
    /// </summary>
    public ImuActions @Imu => new ImuActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Imu" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="ImuActions.AddCallbacks(IImuActions)" />
    /// <seealso cref="ImuActions.RemoveCallbacks(IImuActions)" />
    public interface IImuActions
    {
        /// <summary>
        /// Method invoked when associated input action "Motion" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMotion(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Quit" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnQuit(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SizeChange" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSizeChange(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "DisableGyro" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDisableGyro(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ResetGyro" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnResetGyro(InputAction.CallbackContext context);
    }
}
